### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by enriquemasa** [ORNL-Fusion/xolotl#6]
I am getting the following error when trying to compile with PETSC 3.9

[ 25%] Building CXX object xolotlSolver/CMakeFiles/xolotlSolver.dir/solverhandler/PetscSolver3DHandler.cpp.o
/Users/a242393/Dropbox/CODES/XOLOTL/xolotl/xolotlSolver/solverhandler/PetscSolver3DHandler.cpp:127:9: error: use of undeclared identifier 'DMDASetBlockFillsSparse'; did
      you mean 'DMDASetBlockFills'?
        ierr = DMDASetBlockFillsSparse(da, dfillsparse.data(), ofillsparse.data());
               ^~~~~~~~~~~~~~~~~~~~~~~
               DMDASetBlockFills
/Users/a242393/Dropbox/CODES/PETSC-INSTALL/include/petscdmda.h:194:29: note: 'DMDASetBlockFills' declared here
PETSC_EXTERN PetscErrorCode DMDASetBlockFills(DM,const PetscInt*,const PetscInt*);

Using the function DMDASetBlockFills works and the code compiles but I haven't checked if the output is correct.

**Comment by rothpc** [comment]
Hello Enrique,

We worked with the PETSc developers to add this DMDASetBlockFillsSparse() function to address a memory usage problem in Xolotl.  The DMDASetBlockFillsSparse() function is currently present in the master branch of the PETSc repository, but has not yet been included in a release as of PETSc version 3.9.3.

To work around this, you can do one of several things:

* Use a build of PETSc's current master branch instead of the stock 3.9.x release.
* Use a build of PETSc version 3.9.x with our patch applied.
* Use a build of Xolotl master branch at revision 598048c8 with a stock PETSc 3.9.x release.  This is the latest version of Xolotl without the memory problem fix.

Please feel free to ask if you want the patch file, or if you've chosen a different workaround but aren't sure how to accomplish it.

Regards,
Phil Roth




> On Jul 19, 2018, at 9:55 AM, Enrique Martinez Saez <notifications@github.com> wrote:
> 
> I am getting the following error when trying to compile with PETSC 3.9
> 
> [ 25%] Building CXX object xolotlSolver/CMakeFiles/xolotlSolver.dir/solverhandler/PetscSolver3DHandler.cpp.o
> /Users/a242393/Dropbox/CODES/XOLOTL/xolotl/xolotlSolver/solverhandler/PetscSolver3DHandler.cpp:127:9: error: use of undeclared identifier 'DMDASetBlockFillsSparse'; did
> you mean 'DMDASetBlockFills'?
> ierr = DMDASetBlockFillsSparse(da, dfillsparse.data(), ofillsparse.data());
> ^~~~~~~~~~~~~~~~~~~~~~~
> DMDASetBlockFills
> /Users/a242393/Dropbox/CODES/PETSC-INSTALL/include/petscdmda.h:194:29: note: 'DMDASetBlockFills' declared here
> PETSC_EXTERN PetscErrorCode DMDASetBlockFills(DM,const PetscInt*,const PetscInt*);
> 
> Using the function DMDASetBlockFills works and the code compiles but I haven't checked if the output is correct.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Philip C. Roth | +1 865 241-1543 | http://ft.ornl.gov/~rothpc

**Comment by rothpc** [comment]
The DMDASetBlockFillsSparse() function is included in PETSc releases as of PETSC version 3.10.
